import * as React from 'react';
import {
    Circle,
    ClipPath,
    Defs,
    Ellipse,
    G,
    Image,
    Line,
    LinearGradient,
    Mask,
    Path,
    Pattern,
    Polygon,
    Polyline,
    RadialGradient,
    Rect,
    Stop,
    Svg,
    Symbol,
    Text,
    TSpan,
    Use,
} from 'react-native-svg';

export const elements: {[node: string]: React.ComponentClass} = {
    'circle': Circle,
    'clipPath': ClipPath,
    'defs': Defs,
    'ellipse': Ellipse,
    'g': G,
    'image': Image,
    'line': Line,
    'linearGradient': LinearGradient,
    'path': Path,
    'pattern': Pattern,
    'polygon': Polygon,
    'polyline': Polyline,
    'radialGradient': RadialGradient,
    'rect': Rect,
    'stop': Stop,
    'svg': Svg,
    'symbol': Symbol,
    'tspan': TSpan,
    'text': Text,
    'use': Use,
    'mask': Mask,
};
